---
apiVersion: v1
kind: Pod
metadata:
  name: indexer
  labels:
    app: indexer
spec:
  restartPolicy: Always
  containers:
    - name: indexer
      image: wngud1/indexer:0.0.7
      imagePullPolicy: IfNotPresent
      envFrom:
        - secretRef:
            name: indexer-secret